RealEstateApp/RealEstateApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    
]

RealEstateApp/app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("listing/",views.ListingsListView.as_view(), name="listing"),
    path("listing/<int:pk>/",views.ListingDetailView.as_view(), name="listing-detail"),
    path("agent/", views.AgentsListView.as_view(), name="agent",),
    path("agent/<int:pk>/", views.AgentsDetailView.as_view(), name="agent-detail"),
]

RealEstateApp/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MaxValueValidator, MinValueValidator 


class CustomUser(AbstractUser):

    phonenumber = PhoneNumberField(blank=True, help_text='Phonenumber')
    def __str__(self):
        return self.username
    

class Agent(AbstractUser):
    user = models.OneToOneField(CustomUser, unique=True, on_delete=models.CASCADE)
    profile = models.ImageField(blank=True, null=True)
    first_name = models.CharField(max_length=255, verbose_name="Firstname")
    last_name = models.CharField(max_length=255, verbose_name="Lastname")
    groups = models.ManyToManyField(Group, related_name='agent_set')  
    user_permissions = models.ManyToManyField(Permission, related_name='agent_set')

    class Meta:
        verbose_name = "Agent"
    def __str__(self) -> str:
        return f"Agent - {self.first_name} {self.last_name}"

class AgentRating(models.Model):
    agent = models.ForeignKey(Agent,on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)
    rating_count = models.IntegerField(default=0)
    average_rating = models.FloatField(default=0.0)


    def calculate_rating(self):
        if self.rating_count > 0:
            return self.rating / self.rating_count
        return 0.0
    
    def save(self, *args, **kwargs):
        if not self.average_rating:
            self.average_rating = self.calculate_rating()
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f"{self.agent.first_name} {self.agent.last_name} - {self.average_rating} rating"
    
    

RealEstateApp/templates/app/agent-detail.html
<p>{{object.first_name}}</p>
<p>{{object.last_name}}</p>

RealEstateApp/templates/app/agent.html
{% extends '_base.html' %}


{% block content %}

{% load custom_filters %}

<section>
    <h1 class="text-2xl font-bold ">Some Nearby Agents</h1>

    <form class="flex items-center max-w-full mx-auto mt-4">   
      
        <div class="relative w-full">
            <input type="text" id="search_here" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-stone-500 focus:border-stone-500 block w-full ps-4 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-stone-500 dark:focus:border-stone-500" placeholder="Enter Agents Name" required />
        </div>

    </form>
</section>
<section class="mt-12">
    <div id="box" class="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-3 justify-center">
        {% for item in object_list %}      
          <div class="max-w-xs bg-white border p-2 border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
                <img class="rounded-t-lg " src="https://github.com/ozgrozer/100k-faces/blob/master/docs/0/8/008002.jpg?raw=true" alt="" />
            </a>
            <p class="my-2">{{item.first_name}} {{item.last_name}}</p>
            <div class="flex gap-3 items-center">
                {% for rating in item.agentrating_set.all %}
                <div class="flex gap-1">
                    {% with number=rating.average_rating %}
    

                    {% with number|split_decimal as parts %}

                       {% with parts|make_range as star %} 
                            {% if star.2%}
                                {% for i in star.0 %} 
                                    <i class='bx bxs-star' ></i>
                                {% endfor %} 
                                <i class='bx bxs-star-half' ></i>
                                {% for i in star.1 %} 
                                    <i class='bx bx-star' ></i>
                                {% endfor %} 
                            {% else %}
                                {% for i in star.0 %} 
                                    <i class='bx bxs-star' ></i>
                                {% endfor %} 
                                {% for i in star.1 %} 
                                <i class='bx bx-star' ></i>
                                {% endfor %} 
                            {% endif %}
                        {%endwith%}
                    {% endwith %}
                {% endwith %}
                </div>
                <p>{{rating.average_rating}} reviews</p>
                {% empty %}
                <div class="flex gap-1">
                    <i class='bx bx-star' ></i>
                    <i class='bx bx-star' ></i>
                    <i class='bx bx-star' ></i>
                    <i class='bx bx-star' ></i>
                    <i class='bx bx-star' ></i>
                </div>
                <p>0 reviews</p>
                {% endfor %}
           </div>
           <div class="my-6">
            <a href="{% url 'agent-detail' item.id %}" class="text-gray-900 hover:text-white border border-gray-800 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-12 py-2.5 text-center me-2 my-4 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800">View Profile</a>
           </div>
        </div>
        {% endfor %}
    </div>

    
</section>

{% include 'app/pagination.html' %}
{% endblock %}

{% block scripts %}
<script>
    const data = '{{qs_json}}'
    const rdata = JSON.parse(data.replace(/&quot;/g,'"'))
    const input = document.getElementById('search_here')
    const box = document.getElementById('box')

    let filteredArr = []
    input.addEventListener('keyup',(e)=>{
        box.innerHTML = ""
        filteredArr = rdata.filter(agents=>((agents['first_name'] + agents['last_name']).toLowerCase()).includes((e.target.value).toLowerCase()))
        if (filteredArr.length > 0){
            filteredArr.map(item=>{
                box.innerHTML += `<div class="max-w-xs bg-white border p-2 border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
                <img class="rounded-t-lg " src="https://github.com/ozgrozer/100k-faces/blob/master/docs/0/8/008002.jpg?raw=true" alt="" />
            </a>
            <p class="my-2">${item.first_name} ${item.last_name}</p>
            <div class="flex gap-3 items-center">
                <div class="flex gap-1">
                    <i class='bx bxs-star'></i>
                    <i class='bx bxs-star'></i>
                    <i class='bx bxs-star' ></i>
                    <i class='bx bxs-star' ></i>
                    <i class='bx bxs-star-half' ></i>
                </div>
                <p>${item.average_rating} reviews</p>
           </div>
           <div class="my-6">
            <a href="/agent/${item.id}" class="text-gray-900 hover:text-white border border-gray-800 hover:bg-gray-900 focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-12 py-2.5 text-center me-2 my-4 dark:border-gray-600 dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-800">View Profile</a>
           </div>
           
        </div>`
            })
        }
        else{
            box.innerHTML += `<b>No results found</b>`
        }
    })
</script>
{% endblock %}

RealEstateApp/templates/app/card.html
<div id = "card" class="max-w-fit bg-white border border-stone-200 rounded-lg shadow dark:bg-stone-800 dark:border-stone-700">
    <a href="#">
        <img class="rounded-t-lg" src="https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="" />
    </a>
    <div class="p-5">
        <a href="#">
            <div class="flex items-center gap-3 py-1">
                <i class='bx bxs-map' ></i>
                <p>{{item.property.address}}</p>
            </div>
        </a>
        <div> 
            <div class="lg:flex py-1 gap-3">
                <div class="flex items-center gap-1">
                    <i class='bx bxs-bed' ></i>
                    <p>{{item.property.bedrooms}}</p>
                </div>
                <div class="flex items-center gap-1">
                    <i class='bx bxs-bath' ></i>
                    <p>{{item.property.bathrooms}}</p>
                </div>
        </div>
            <div class="py-2">
                <div class="flex py-1 items-center gap-3">
                    <i class='bx bxs-area' ></i>
                    <p class="flex">{{item.property.square_footage|floatformat}} sqm</p>
                </div>
                <div class="flex py-1 items-center gap-3">
                    <i class='bx bxs-home' ></i>
                    <p>{{item.property.property_type}}</p>
                </div>
            </div>
        </div>
        <div class="flex items-center my-4">
            <a href="{% url 'listing-detail' item.id %}" class="text-white bg-stone-800 hover:bg-stone-900 focus:outline-none focus:ring-4 focus:ring-stone-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-stone-800 dark:hover:bg-stone-700 dark:focus:ring-stone-700 dark:border-stone-700">View Details</a>
            <p class="font-bold rounded-lg text-md px-5 py-2.5 me-2 mb-2">ETB {{item.property.price|floatformat}}</p>
        </div>
    </div>
</div>

RealEstateApp/templates/app/filter.html
<section class="mb-8 mt-4 gap-y-3">
    <div>
        <div>
            <div class="flex">
                <div class="w-full">
                    <form class="flex items-center justify-between">
                        <div class="w-8/12">
                            <label for="address-search" class="sr-only">Search</label>
                            <div class="relative w-11/12">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
                                    </svg>
                                </div>
                                <input onkeydown="getAddress(this)"type="text" id="address-search" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Search" required="">
                            </div>
                        </div>
                        <div class="w-6/12 mx-auto flex gap-3 justify-end">
                            <select id="propertyType" onChange = "getOption(this)" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-2/12 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                              <option selected>Type</option>
                              <option value="Single family home">Single family home</option>
                              <option value="Townhouse">Townhouse</option>
                              <option value="Condominium">Condominium</option>
                              <option value="Apartment">Apartment</option>
                              <option value="Office building">Office building</option>
                              <option value="Retail space">Retail space</option>
                              <option value="Industrial property">Industrial property</option>
                              <option value="Land">Land</option>
                            </select>
    
                            <button id="dropdownDefault" data-dropdown-toggle="dropdown"
                            class="text-stone-900 bg-gray-50 border border-gray-300 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
                            type="button">
                            Price
                            <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                              xmlns="http://www.w3.org/2000/svg">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                            </svg>
                          </button>
                              
                              
                              <select id="bedrooms" onChange = "getOption(this)" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-fit p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                                <option selected>Bed</option>
    
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                              </select>
    
                              <select id="bathrooms" onChange = "getOption(this)" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-fit p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                                <option selected>Bath</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                              </select>

                              <select id="yearBuilt" onChange = "getOption(this)" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-2/12 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                                <option selected>Year</option>
                                <option value="Before 1950">Before 1950</option>
                                <option value="1950-1960">1950 - 1960</option>
                                <option value="1960-1970">1960 - 1970</option>
                                <option value="1970-1980">1970 - 1980</option>
                                <option value="1980-1990">1980 - 1990</option>
                                <option value="1990-2000">1990 - 2000</option>
                                <option value="2000-2010">2000 - 2010</option>
                                <option value="2010-2020">2010 - 2020</option>
                                <option value="2020-2023">2020 - 2023</option>
                              </select>
                              
                            </div>
                        </div>
                    </form>

            </div>
        </div>
        <div class="mt-3" id="filter-container">

        </div>
            
    </div>
 
    <div id="dropdown" class="z-10 hidden w-56 p-3 bg-white rounded-lg shadow dark:bg-gray-700">
        <h6 class="mb-3 text-sm font-medium text-gray-900 dark:text-white">
          Price
        </h6>
        <div class="flex justify-evenly gap-2">
            <div>
                <label for="min" class="block mb-2 text-xs font-medium text-gray-900 dark:text-white">Min</label>
                <input type="text" id="min" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" value="10000" required />
            </div>
            <div>
                <label for="max" class="block mb-2 text-xs font-medium text-gray-900 dark:text-white">Max</label>
                <input  type="text" id="max" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" value="10000000" required />
            </div>
        </div>
        <button onClick="getPrice()">Filter by price</button>
      </div>
    

</section>

RealEstateApp/templates/app/hero.html
<section class="space-y-8 h-screen flex ">
   <div>
    <div class="space-y-10 mt-14">
        <div class="space-y-6">
            <h1 class="text-5xl font-bold">Your Dream Home Awaits</h1>
            <p class="text-lg">Find your perfect property effortlessly. Start your journey now.</p>
        </div>
        <form class="w-2/3">
            <div class="flex">
                <button id="dropdown-button" data-dropdown-toggle="dropdown" class="flex-shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-e-0 border-gray-300 dark:border-gray-700 dark:text-white rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-300 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800" type="button">All categories
                    <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
        </button>
                <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 ">
                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Single family home</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Townhouse</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Condominium</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Apartment</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Office building</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Retail space</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Industrial property</a>
                    </li>
                    <li>
                        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Land</a>
                    </li>
                    </ul>
                </div>
                <div class="relative w-full">
                    <input type="search" id="search-dropdown" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-lg rounded-s-gray-100 rounded-s-2 border border-gray-300 focus:ring-stone-500 focus:border-stone-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-stone-500" placeholder="Search" required />
                    <button type="submit" class="absolute top-0 end-0 p-2.5 h-full text-sm font-medium text-white bg-stone-700 rounded-e-lg border border-stone-700 hover:bg-stone-800 focus:ring-4 focus:outline-none focus:ring-stone-300 dark:bg-stone-600 dark:hover:bg-stone-700 dark:focus:ring-stone-800">
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
          </svg></button>
                </div>
            </div>
        </form>
    </div>
    <div class="flex gap-5 mt-24">
        <div class="space-y-3">
            <i class='bx bxs-wallet text-4xl'></i>
            <p class="font-bold text-3xl">15.4M+</p>
            <p class="w-2/3">Owned from Properties transactions</p>
        </div>

        <div class="space-y-3">
            <i class='bx bxs-map-pin text-4xl'></i>
            <p class="font-bold text-3xl">25k+</p>
            <p class="w-2/3">Properties for Buy & sell Successfully</p>
        </div>

        <div class="space-y-3">
            <i class='bx bxs-hot text-4xl'></i>
            <p class="font-bold text-3xl">500+</p>
            <p class="w-2/3">Daily completed transactions</p>
        </div>

        <div class="space-y-3">
            <i class='bx bxs-wink-smile text-4xl' ></i>
            <p class="font-bold text-3xl">600+</p>
            <p class="w-2/3">Regular Clients</p>
        </div>
    </div>
   </div>
    
</section>

RealEstateApp/templates/app/home.html
{% extends "_base.html" %}

{% block content %}
<main>
    {% include 'app/hero.html' %}
    <section>
        <div class="flex justify-between items-center my-10">
            <h1 class="text-2xl font-bold ">Featured Properties</h1>
            <a href="{% url 'listing' %}" class="flex gap-1 items-center hover:underline">Explore more <i class='bx bx-right-arrow-alt'></i></a>
        </div>
        <div class="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-5">
            {% for item in object_list|slice:"6" %}      
               {% include 'app/card.html' %}
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

RealEstateApp/templates/app/listing-detail.html
<p>{{ object.property.title }}</p>
<p>{{ object.property.city }}</p>
<p>{{ object.property.state_province }}</p>
<p>{{ object.property.property_type }}</p>
<p>{{ object.property.postal_code }}</p>
<p>{{ object.property.square_footage }}</p>
<p>{{ object.property.bedrooms }}</p>
<p>{{ object.property.bathrooms }}</p>
<p>{{ object.property.year_built }}</p>
<p>{{ object.property.description }}</p>
<p>{{ object.property.price }}</p>
<p>{{ object.property.status }}</p>
<p>{{ object.property.location }}</p>
<p>{{ object.property.amenities.title }}</p>

RealEstateApp/templates/app/pagination.html
<div class="flex flex-col items-center my-8">
    <span class="text-sm text-gray-700 dark:text-gray-400">
        Page <span class="font-semibold text-gray-900 dark:text-white">{{ page_obj.number }}</span> of <span class="font-semibold text-gray-900 dark:text-white">{{ page_obj.paginator.num_pages }}  </span> 
    </span>
    <div class="inline-flex mt-2 xs:mt-0">
      {% if page_obj.has_previous %}
      <a href="?page=1" class="flex items-center justify-center px-4 h-10 text-base font-medium text-white bg-stone-900 hover:bg-gray-900 dark:bg-gray-800 border-s dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          First
      </a>
        <a href="?page={{page_obj.previous_page_number}}" class="flex items-center justify-center px-4 h-10 text-base font-medium text-white bg-stone-900 hover:bg-gray-900 dark:bg-gray-800 border-s dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
            </svg>  
          Prev
        </a>
      {% endif %}   
      {% if page_obj.has_next %} 
        <a href="?page={{ page_obj.next_page_number }}" class="flex items-center justify-center px-4 h-10 text-base font-medium text-white bg-stone-900 hover:bg-gray-900 dark:bg-gray-800 border-s dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"> 
          Next
          <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
        </a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="flex items-center justify-center px-4 h-10 text-base font-medium text-white bg-stone-900 hover:bg-gray-900 dark:bg-gray-800 border-s dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
          Last
      </a>
      {% endif %}
    </div>
  </div>